version: '2'
services:
  jhispter-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/jhispter/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhispter
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
